### ISSUE TITLE
Error code 8 when trying to cash out

### ISSUE THREAD

**Issue by ghost** [compumatrix/portal#25] opened 2016-09-18 10:29 UTC
20 European members is getting the Error 8 message when trying to cash out.
They are from Lithuania, Portugal, the Nederlands, Ireland and one Swedish member, 
so the problem is not tied to one area only

Inga B Molin, 
RR Europe

**Comment by BlueMagic1** [comment] 2016-09-18 10:36
2 Pinoy members likewise reported the same issue at the Forum.

It probably is caused by closing the Cashout box after such a long time for the "Processing" status to change.  Baka "traffic" lng.  :)

**Comment by Lovejoy2** [comment] 2016-09-18 10:52
My one for Company also has the error 8 so will wait for instructios

**Comment by coky1** [comment] 2016-09-18 12:36
I report this issue too

**Comment by cniijane-compumatrix** [comment] 2016-09-18 22:02
This came up on two 'cashouts'  One gave back Error code 8 and nothing more (Horus)

and for Savedman it gave back
An Error occurred while processing your request. 
ERROR CODE: 8 - You reached your daily limit of your API

That tells me there is an API limit that needs to be either lifted or checked in the coding.

**Closed as completed** 2016-09-24 01:18 UTC
